name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify buildozer.spec exists
        run: |
          cd $GITHUB_WORKSPACE
          echo "Current directory: $PWD"
          ls
          if [ ! -f buildozer.spec ]; then
            echo "Error: buildozer.spec not found in the repository root!"
            exit 1
          fi

      - name: Install dependencies and Android SDK
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip git zip unzip openjdk-17-jdk wget
          pip install --upgrade pip
          pip install cython buildozer kivy

          mkdir -p $HOME/.buildozer/android/cmdline-tools/latest

          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $HOME/.buildozer/android/cmdline-tools/temp
          mv $HOME/.buildozer/android/cmdline-tools/temp/cmdline-tools/* $HOME/.buildozer/android/cmdline-tools/latest/
          rm -rf $HOME/.buildozer/android/cmdline-tools/temp

          export ANDROID_HOME=$HOME/.buildozer/android
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH

          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --version
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;36.0.0"

      - name: Build APK
        run: |
          cd $GITHUB_WORKSPACE
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: TestApp-APK
          path: bin/*.apk
